version: "3"
services:
  db:
    image: mongo:latest
    restart: always 
    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: dev123
    volumes:
      - mongodb_data:/data/db
    networks:
      - docker_network
  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file: ./.env
    command: yarn dev
    restart: always 
    networks:
      - docker_network

volumes:
  mongodb_data: {}

networks:
  docker_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.21.0.0/16